fix(composer): COMPOSER_HOME setup
le-phare/ansible-deploy pull request #39
Opened 2023-07-27 15:39 UTC by pierreboissinot

Fixes to https://github.com/le-phare/ansible-deploy/issues/36

2023-07-28 07:10 UTC, thislg requested changes

2023-07-28 07:10 UTC, thislg commented on defaults/main.yml
> +lephare_composer_home: '~/.composer'
Depuis Composer 2 ça s'installe dans `${XDG_CONFIG_HOME-.config}/composer`

```suggestion
lephare_composer_home: '~/.config/composer'
```

2023-07-28 07:48 UTC, pierreboissinot commented on defaults/main.yml
> +lephare_composer_home: '~/.composer'
Oui il s'agit de la valeur par défaut qui serait surchargée par $COMPOSER_HOME https://getcomposer.org/doc/03-cli.md#composer-home

Peu m'importe

2023-07-31 08:47 UTC, aegypius commented
@pierreboissinot do not use this kind of branch name, it's not properly supported as a docker tag nor a galaxy branch

2023-07-31 09:05 UTC, pierreboissinot commented
> @pierreboissinot do not use this kind of branch name, it's not properly supported as a docker tag nor a galaxy branch

le `/` ?

2023-07-31 09:14 UTC, aegypius commented
oui

2023-07-31 09:19 UTC, pierreboissinot commented
closing for https://github.com/le-phare/ansible-deploy/pull/42

2023-07-31 09:19 UTC, closed without merging