fix: add sshpass package
le-phare/ansible-deploy pull request #52
Opened 2024-07-02 16:11 UTC by pierreboissinot

J'ai rencontré cette erreur en utilisant la version 1.12.0

> to use the 'ssh' connection type with passwords or pkcs11_provider, you must install the sshpass program

Je ne pense pas que ce soit lié au changement sur la 1.12.0 directement mais peut être indirectement au build de l'image Docker qui a été déclenché, sur laquelle le paquet ne serait plus présent depuis le dernier build (fin 2023) par défaut.

Je n'ai pas creusé plus.

2024-07-02 16:40 UTC, lucasmirloup requested changes

2024-07-02 16:40 UTC, lucasmirloup commented on docker/Dockerfile
>  RUN apk add --no-cache --update bash git mysql-client openssh-client postgresql rsync
```suggestion
RUN apk add --no-cache --update bash git mysql-client openssh-client postgresql rsync sshpass
```
\+ retirer `sshpass` de la ligne d'après (je ne peux pas faire de suggestion sur cette ligne via GitHub)

La 2ème ligne de `apk add` ne sert que pour des dépendances qu'on installe juste le temps de compiler l'image, puis on les supprime juste après.
Pour les dépendances pérennes c'est dans la 1ère.

2024-07-03 05:46 UTC, pierreboissinot commented on docker/Dockerfile
>  RUN apk add --no-cache --update bash git mysql-client openssh-client postgresql rsync
Merci je n'avais outres fait attention

2024-07-03 07:06 UTC, thislg approved these changes

2024-07-03 07:23 UTC, lucasmirloup approved these changes

2024-07-03 07:24 UTC, lucasmirloup commented
J'ai l'impression que le workflow GitHub Action du projet n'est pas prévu pour gérer les PR. Il prend ça comme une branche normale, avec comme nom `merge` : https://github.com/le-phare/ansible-deploy/actions/runs/9772935847/job/26978169397?pr=52#step:8:579

2024-07-03 07:24 UTC, merged

2024-07-03 07:28 UTC, pierreboissinot commented
merci les gars :+1:

2024-07-03 07:54 UTC, pierreboissinot commented
@lucasmirloup @thislg Je vous confirme le bon fonctionnement du fix. J'arrive de nouveau à déployer alors que je n'y arrivais plus avec la 1.12.0