Upgrade Ansible
le-phare/ansible-deploy pull request #56
Opened 2024-07-04 12:41 UTC by pierreboissinot

2024-07-05 07:26 UTC, lucasmirloup requested changes

2024-07-05 07:26 UTC, lucasmirloup commented on docker/Dockerfile
> +RUN pip install --no-cache-dir ansible ansible-core==2.17
Je propose d'autoriser les MAJ des versions "patch" de `ansible-core` : 
```suggestion
RUN pip install --no-cache-dir ansible ansible-core~=2.17.1
```

Voir [Version specifiers - Python Packaging User Guide](https://packaging.python.org/en/latest/specifications/version-specifiers/#id5) et [Compatible release](https://packaging.python.org/en/latest/specifications/version-specifiers/#compatible-release)

2024-07-05 08:00 UTC, pierreboissinot commented on docker/Dockerfile
> +RUN pip install --no-cache-dir ansible ansible-core==2.17
tu as raison @lucasmirloup , ansible-core ne suit pas le semver https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html

2024-07-05 08:14 UTC, lucasmirloup approved these changes

2024-07-05 08:24 UTC, thislg requested changes
La branche n'est pas à jour (on voit des modifs concernant la 1.12.3 qui ont été mergées sur l'autre PR).

2024-07-05 08:46 UTC, pierreboissinot commented
> La branche n'est pas à jour (on voit des modifs concernant la 1.12.3 qui ont été mergées sur l'autre PR).

Ok.

2024-07-05 09:02 UTC, thislg requested changes

2024-07-05 09:02 UTC, thislg commented on CHANGELOG.md
> +## [2.0.0](https://github.com/le-phare/ansible-deploy/compare/v1.12.3...v2.0.0) (2024-07-04)
```suggestion
## [2.0.0](https://github.com/le-phare/ansible-deploy/compare/v1.12.3...v2.0.0) (2024-07-05)
```

2024-07-05 09:20 UTC, thislg approved these changes

2024-07-05 09:21 UTC, pierreboissinot commented
@thislg suivant vos agendas dites-moi mais je peux tester la v2.0.0 cet aprem, la semaine pro je suis en congés.

2024-07-05 09:21 UTC, thislg approved these changes

2024-07-05 09:44 UTC, lucasmirloup approved these changes

2024-07-05 11:09 UTC, pierreboissinot commented
@lucasmirloup @thislg 

Merci, je me suis mis un rappel pour le 15/07 afin de update la date sur le changelog et merge + tester la nouvelle version sur un projet.

2024-07-05 12:05 UTC, thislg commented
Et dans la mesure du possible il faudrait tester sur un projet avant de taguer la version.

2024-07-05 12:58 UTC, pierreboissinot commented
> Et dans la mesure du possible il faudrait tester sur un projet avant de taguer la version.

Ce ne sera pas possible de mon côté, les projets IMA ne sont pas déployable hors CI/CD.
Je demanderai à l'un de vous deux de build en local et de tester un déploiement en preprod vers un server post 2022 (qui a python3).

2024-07-05 14:09 UTC, thislg commented
Tous les commits push donnent lieu à une image docker que tu peux renseigner dans ta configuration Ansible : https://hub.docker.com/layers/lephare/ansible/upgrade-ansible/images/sha256-313b19ce6bee082f82cc2acc2344b63a001eae44212c4d878f8b937aaca52b0d?context=explore

2024-07-16 07:09 UTC, pierreboissinot commented
@thislg @lucasmirloup changelog updated, test réussi sur un serveur avec Python 3.9.2.

J'ai corrigé une erreur dans le readme également

2024-07-16 12:36 UTC, lucasmirloup submitted a review, later dismissed

2024-07-16 13:52 UTC, lucasmirloup approved these changes

2024-07-16 14:04 UTC, thislg approved these changes

2024-07-16 14:36 UTC, pierreboissinot commented
merci pour les reviews

2024-07-16 14:37 UTC, merged