security: use forked install-composer to support channel installation
le-phare/ansible-deploy pull request #66
Opened 2024-09-19 10:31 UTC by pierreboissinot

J'ai fait une [PR ](https://github.com/cbrunnkvist/ansistrano-symfony-deploy/pull/40)sur cbrunnkvist/ansistrano-symfony-deploy mais le projet n'est plus [maintenu](https://github.com/cbrunnkvist/ansistrano-symfony-deploy/issues/36).

Nous avons deux solutions:
- merge dans le fork lephare et utilisé ce fork dans ansible-deploy
- attendre ? Le projet n'a pas bougé depuis 4 ans 

Je suis pour changer les requirements de ansible-deploy pour utiliser notre fork.

Qu'en dites-vous ?

J'ai testé l'image docker les changements fonctionnent comme attendu.

2024-09-19 12:23 UTC, lucasmirloup commented
Je valide l'idée de coder sur notre fork (https://github.com/le-phare/ansistrano-symfony-deploy), et de l'utiliser sur ce repo

2024-09-19 12:26 UTC, lucasmirloup requested changes

2024-09-19 12:37 UTC, pierreboissinot commented on meta/main.yml
> +    version: install-composer
Oui

>merge dans le fork lephare et utilisé ce fork dans ansible-deploy (donc version master et non install-composer)

2024-09-19 13:32 UTC, thislg commented on meta/main.yml
> +    version: install-composer
On s'est déjà posé la question, en effet le fork est la solution. Pour commencer tu peux faire ta PR sur le fork.

2024-09-19 13:49 UTC, pierreboissinot commented on meta/main.yml
> +    version: install-composer
https://github.com/le-phare/ansistrano-symfony-deploy/pull/1

2024-09-19 13:52 UTC, pierreboissinot commented
@thislg @lucasmirloup unef ois que https://github.com/le-phare/ansistrano-symfony-deploy/pull/1 est merged, je veux bien un coup de main pour savoir ce qu'il faut faire pour la prochaine release. depuis qu'on utilise "make release" je crois je n'en n'ai pas faite.

2024-10-24 14:12 UTC, lucasmirloup approved these changes

2026-07-31 12:17 UTC, lucasmirloup commented
Je ferme pour inactivité, à rouvrir au besoin :+1:

2026-07-31 12:17 UTC, closed without merging